name: Update Statstics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"
    - cron: "0 8 * * 3"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Restore cached dependencies
        id: restore-cached-dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache/save@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: ${{ steps.restore-cached-dependencies.outputs.cache-primary-key }}

      - name: Install dependencies
        run: npm install

      - name: Get latest Chrome version
        id: chrome-version
        run: |
          VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Restore cached Chrome
        id: restore-cached-chrome
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cache/puppeteer
          key: puppeteer-chrome-${{ runner.os }}-${{ steps.chrome-version.outputs.version }}
          restore-keys: |
            puppeteer-chrome-${{ runner.os }}-${{ steps.chrome-version.outputs.version }}
            puppeteer-chrome-${{ runner.os }}-

      - name: Install Chrome
        run: npx puppeteer browsers install chrome

      - name: Cache Chrome
        id: cache-chrome
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cache/puppeteer
          key: ${{ steps.restore-cached-chrome.outputs.cache-primary-key }}

      - name: Update
        run: node index.js
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "github-actions-bot <support+actions@github.com>" -b release -d ./dist/ --add
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}