name: Update Language Statistics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Get current date
        id: get-current-date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Restore cached dependencies
        id: restore-cached-dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache/save@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: ${{ steps.restore-cached-dependencies.outputs.cache-primary-key }}

      - name: Install dependencies
        run: npm install

      - name: Restore cached repositories list
        id: restore-cached-repositories-list
        uses: actions/cache/restore@v5
        with:
          path: |
            ./repositories-list
          key: repositories-list-${{ steps.get-current-date.outputs.today }}
          restore-keys: |
            repositories-list-${{ steps.get-current-date.outputs.today }}
            repositories-list-

      - name: List repositories
        run: node list-repositories.js
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIST_REPOSITORIES_TOKEN: ${{ secrets.LIST_REPOSITORIES_TOKEN }}

      - name: Cache repositories list
        id: cache-repositories-list
        uses: actions/cache/save@v5
        with:
          path: |
            ./repositories-list
          key: ${{ steps.restore-cached-repositories-list.outputs.cache-primary-key }}

      - name: Update language statistics
        run: node update-language-statistics.js
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIST_REPOSITORIES_TOKEN: ${{ secrets.LIST_REPOSITORIES_TOKEN }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "github-actions-bot <support+actions@github.com>" -b main -d ./deploy/ --add
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}